version: '3.3'

services:

  mssql:
    container_name: MSSQL-Server
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"